---
# tasks file for ossec-server

- name: Install the correct repository
  include: "RedHat.yml"
  when: ansible_os_family == "RedHat"

- name: Install the correct repository
  include: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: Installing SSL files.
  copy: src={{ item }}
        dest=/var/ossec/etc/{{ item }}
        owner=root
        group=root
        mode=0660
  with_items:
    - sslmanager.key
    - sslmanager.cert
  tags:
    - config

- name: Configure the shared-agent.conf
  template: src=var-ossec-etc-shared-agent.conf.j2
            dest=/var/ossec/etc/shared/agent.conf
            owner=ossec
            group=ossec
            mode=0644
  notify: restart ossec-server
  tags:
    - init
    - config

- name: Installing the local_rules.xml
  template: src=var-ossec-rules-local_rules.xml.j2
            dest=/var/ossec/rules/local_rules.xml
            owner=root
            group=root
            mode=0644
  notify: restart ossec-server
  tags:
    - init
    - config
    - rules

- name: Install RHEL6 CIS Root Checks
  get_url:
    url: https://raw.githubusercontent.com/ossec/ossec-hids/master/src/rootcheck/db/cis_rhel6_linux_rcl.txt
    dest: /var/ossec/etc/shared/cis_rhel6_linux_rcl.txt
    mode: 0660
    owner: root
    group: ossec 

- name: Set Distribution CIS filename for Debian/Ubuntu
  set_fact:
    cis_distribution_filename: cis_debian_linux_rcl.txt
  when: ansible_os_family == "Debian"

- name: Set Distribution CIS filename for RHEL5
  set_fact:
    cis_distribution_filename: cis_rhel5_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

- name: Set Distribution CIS filename for RHEL6
  set_fact:
    cis_distribution_filename: cis_rhel6_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Set ossec deploy facts for RedHat
  set_fact:
    ossec_server_config_filename: ossec-server.conf
    ossec_init_name: ossec-hids
  when: ansible_os_family == "RedHat"

- name: Set ossec deploy facts for Debian
  set_fact:
    ossec_server_config_filename: ossec.conf
    ossec_init_name: ossec
  when: ansible_os_family == "Debian"

- name: Configure the ossec-server
  template: src=var-ossec-etc-ossec-server.conf.j2
            dest=/var/ossec/etc/{{ ossec_server_config_filename }}
            owner=root
            group=root
            mode=0644
  notify: restart ossec-server
  tags:
    - init
    - config
