---
# Tasks specific for RedHat systems

- name: RedHat | Set some facts
  set_fact:
    ansible_distribution: centos
  when: ansible_distribution == "RedHat"

- name: RedHat | Install atomicorp repo
  yum: name=https://www.atomicorp.com/channels/atomic/centos/{{ansible_distribution_major_version}}/x86_64/RPMS/atomic-release-1.0-19.el{{ansible_distribution_major_version}}.art.noarch.rpm state=present

- name: RedHat | Install epel repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm state=present


- name: RedHat | Install ossec-hids-server
  yum: pkg={{ item }}
       state=present
  with_items:
    - ossec-hids
    - ossec-hids-server
  tags:
    - init

